# Generated by Django 6.0.7 on 2026-07-15 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umrah', '0003_package_alter_customer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOCUMENTS_VERIFIED', 'Documents Verified'), ('VISA_PROCESSING', 'Visa Processing'), ('APPROVED', 'Approved'), ('TRAVELED', 'Traveled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Canceled')], default='PENDING', max_length=200)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='umrah.customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='umrah.package')),
            ],
        ),
    ]
