# Generated by Django 6.0.7 on 2026-07-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umrah', '0006_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahapplication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
