# Generated by Django 6.0.7 on 2026-07-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umrah', '0007_umrahapplication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
